name: magic_card
description: MTG-Card renderer, and utility package.
repository: https://github.com/ArcaneArts/magic_card
version: 1.0.1+2
environment:
  sdk: ^3.3.2
#dependency_overrides:
#  mtg:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/mtg/"
#  nonsense_foil:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/nonsense-foil"

dependencies:
  flutter:
    sdk: flutter
  memcached: ^1.1.0
  scryfall_api: <=2.2.0
  cached_network_image: <=3.4.1
  fast_log: <=1.0.7
  mtg: ^1.0.2+1
  nonsense_foil: <=2.0.0


dev_dependencies:
  lints: ^5.1.1
