name: magic_card
description: MTG-Card renderer, and utility package.
repository: https://github.com/ArcaneArts/magic_card
version: 1.0.1+dev.5
environment:
  sdk: ^3.3.2
dependencies:
  flutter:
    sdk: flutter
  foil: ^0.9.0+1
  memcached: ^1.1.0
  scryfall_api: <=2.2.0
  cached_network_image: <=3.4.1
  fast_log: ^1.0.7

dev_dependencies:
  lints: ^5.1.1
flutter: