name: magic_card
description: MTG-Card renderer, and utility package.
repository: https://github.com/ArcaneArts/magic_card
version: 1.3.0
environment:
  sdk: ^3.3.2
#dependency_overrides:
#  mtg:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/mtg/"
#  nonsense_foil:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/nonsense-foil"

dependencies:
  flutter:
    sdk: flutter
  memcached: ">=1.1.0 <2.0.0"
  scryfall_api: ">=2.5.0 <3.0.0"
  cached_network_image: ">=3.4.1 <4.0.0"
  fast_log: ">=1.0.7 <2.0.0"
  mtg: ">=1.0.3 <3.0.0"
  nonsense_foil: ">=0.9.0+2 <3.0.0"
  skeletonizer: ">=2.1.0 <3.0.0"


dev_dependencies:
  lints: ^6.0.0
